apiVersion: v1
kind: Pod
metadata:
  name: nginx-rediness-http-fail
spec:
  containers:
    - name: nginx-rediness
      image: nginx:1.15-alpine
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 81
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 1
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 1