#!groovy

pipeline {
  agent any
  stages {
    stage('Checkout') {
        steps {
            git url: 'https://github.com/spring-projects/spring-petclinic.git', credentialsId: 'spring-projects', branch: 'master'
        }
    }
    stage('Maven Install') {
      agent {
        docker {
          image 'maven:3.5.0'
        }
      }
      steps {
        sh 'mvn clean install'
      }
    }
    stage('Docker Build') {
      agent any
      steps {
        sh 'docker build -t deepborah/spring-petclinic:latest .'
      }
    }
    stage('Docker Push') {
      agent any
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
          sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
          sh 'docker push deepborah/spring-petclinic:latest'
        }
      }
    }
  }
}