apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-petclinic-app
  labels:
    app: spring-petclinic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic-app
  template:
    metadata:
      labels:
        app: spring-petclinic-app
    spec:
      containers:
        - name: spring-petclinic-app
          image: deepborah/spring-petclinic
          ports:
            - containerPort: 8080