apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-app
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: petclinicaks
spec:
  selector:
    app: spring-petclinic-app
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer