apiVersion: v1
kind: Service
metadata:
   name: petclinic-loadBalancer
   labels:
     name: loadbalancer-service
     app: petclinic-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    name: petclinic-app-pod
    app: petclinic-app