apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo2
  namespace: mem-cpu-quota
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "4Gi"
          cpu: "2"
        requests:
          memory: "1Gi"
          cpu: "1"